name: 'Check Changed Folder'
description: 'Checks if specified folders have been changed'
inputs:
  folders:
    description: 'List of folders to check'
    required: true
    default: '[]'
outputs:
  changed:
    description: 'Object containing the name and change status of each folder'
runs:
  using: 'node12'
  main: 'index.js'