name: Check Folder Action
description: Checks if a specified folder has been changed in a repository
inputs:
  folder:
    description: 'The folder path to check for changes'
    required: true
outputs:
  changed:
    description: 'Indicates whether the folder has been changed'
    value: ${{ steps.check_folder.outputs.changed }}
runs:
  using: 'node16'
  main: 'index.js'
