name: Check Folder Workflow

on:
  push:
    branches:
      - main

jobs:
  check_folder_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Run Check Folder Action
        id: check_folder
        uses: ./ # Path to your action folder
        
        with:
          folder: 'path/to/folder' # Set the directory path you want to check
          
      - name: Print Changed Status
        run: echo "Folder changed: ${{ steps.check_folder.outputs.changed }}"
